LEGACY_NOISY_POLICY_TEXT_BEFORE = (
    "Terms of Service | Concise Top Stories General India Kerala News Karnataka More "
    "Quick Menu Facts About Us Privacy Policy Terms of Service Contact Us Terms of Service "
    "Effective Date: November 7, 2024 Welcome to Concise, a news aggregation platform. "
    "By accessing or using Concise, you agree to these Terms of Service. "
    "1. Use of the Platform You may use the platform for personal, non-commercial purposes. "
    "2. User-Generated Content You retain ownership of your content but grant us a license to use it. "
    "3. Intellectual Property Rights All platform content is protected by copyright and trademark law. "
    "4. Third-Party Links and Content We are not responsible for third-party sites. "
    "5. Privacy Review our Privacy Policy to understand our data practices. "
    "6. Disclaimer of Warranties The platform is provided as is and as available. "
    "7. Limitation of Liability We are not liable for indirect or consequential damages. "
    "8. Indemnification You agree to indemnify and hold Concise harmless. "
    "9. Modifications to Terms We may modify these Terms at any time. "
    "10. Termination We may terminate or suspend access to the platform. "
    "11. Governing Law These Terms are governed by the laws of Delhi, India. "
    "12. Contact Us Email care@concise.plus Address Delhi, India. "
    "Continue your knowledge journey! Click here See full article. "
    "Name First Last Email Phone This field is hidden when viewing the form Confirm Email "
    "This field is hidden when viewing the form Quote Source Get Your FREE Design Rendering "
    "Before It's Gone! Your $995 Value Awaits, No Strings Attached. Heading Text #1 "
    "Request a Callback Fill out the form below, and we'll call you within 24 hours. "
    "Phone This field is for validation purposes and should be left unchanged. Terms of Service Close"
)

LEGACY_NOISY_POLICY_TEXT_AFTER = (
    "Terms of Service | Concise Top Stories General India Kerala News Karnataka More "
    "Quick Menu Facts About Us Privacy Policy Terms of Service Contact Us Terms of Service "
    "Effective Date: November 7, 2024 Welcome to Concise, a news aggregation platform. "
    "By accessing or using Concise, you agree to these Terms of Service. "
    "1. Use of the Platform You may use the platform for personal, non-commercial purposes. "
    "2. User-Generated Content You retain ownership of your content but grant us a license to use it. "
    "3. Intellectual Property Rights All platform content is protected by copyright and trademark law. "
    "4. Third-Party Links and Content We are not responsible for third-party sites. "
    "5. Privacy Review our Privacy Policy to understand our data practices. "
    "6. Disclaimer of Warranties The platform is provided as is and as available. "
    "7. Limitation of Liability We are not liable for indirect or consequential damages. "
    "8. Indemnification You agree to indemnify and hold Concise harmless. "
    "9. Modifications to Terms We may modify these Terms at any time. "
    "10. Termination We may terminate or suspend access to the platform. "
    "11. Governing Law These Terms are governed by the laws of Delhi, India. "
    "12. Contact Us Email care@concise.plus Address Delhi, India. "
    "Continue your knowledge journey! Click here See full article. "
    "Name First Last Email Email This field is hidden when viewing the form Confirm Email "
    "This field is hidden when viewing the form Quote Source Get Your FREE Design Rendering "
    "Before It's Gone! Your $995 Value Awaits, No Strings Attached. Heading Text #1 "
    "Request a Callback Fill out the form below, and we'll call you within 24 hours. "
    "Email This field is for validation purposes and should be left unchanged. Terms of Service Close"
)
